services:
  postgres:
    image: postgres:16-alpine
    container_name: 21day-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 21day
    ports:
      - "5432:5432"
    volumes:
      - 21day_pgdata:/var/lib/postgresql/data

volumes:
  21day_pgdata:
